version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-2:274201610284:task-definition/eureka-server:1"
        LoadBalancerInfo:
          ContainerName: "eureka-server"
          ContainerPort: "8761"
# Optional properties
        PlatformVersion: "LATEST"
